name: Flutter

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            library-task: "swift-build --interface --platform macos-flutter",
            xcframework-task: "swift-build-xcframework --platform macos-flutter"
          }

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Python Requirements (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          python -m pip install -r requirements.txt
          echo "$PWD\.venv\Scripts" >> $GITHUB_PATH

      - name: Python Requirements (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install -r requirements.txt
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.30.0"

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: "1.10.0"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.4"
          channel: "stable"

      - name: Verify
        run: |
          python3 --version
          cmake --version
          ninja --version
          flutter --version

      - name: Conan
        run: python3 xplpc.py conan-setup

      - name: Build Native Library
        run: |
          python3 xplpc.py ${{ matrix.config.library-task }}
          python3 xplpc.py ${{ matrix.config.xcframework-task }}

      - name: Test
        run: python3 xplpc.py flutter-test
