name: Kotlin Android

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS Latest Clang",
            os: macos-13
          }

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Python Requirements
        run: |
          python3 -m pip install -r requirements.txt --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/Library/Python/3.9/bin" >> $GITHUB_PATH

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: "3.31.2"

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: "1.10.0"

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Install NDK (only when use cpm)
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Verify
        run: |
          python3 --version
          cmake --version
          ninja --version
          java -version
          ndk-build -version

      - name: Get AVD info
        uses: ./.github/actions/get-avd-info
        id: avd-info
        with:
            api-level: 34

      - name: Conan (only when use conan)
        run: python3 xplpc.py conan-setup

      - name: Build
        run: python3 xplpc.py kotlin-build --platform android
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build AAR
        run: python3 xplpc.py kotlin-build-aar --platform android

      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: ${{ steps.avd-info.outputs.arch }}
          target: ${{ steps.avd-info.outputs.target }}
          disable-animations: true
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          script: python3 xplpc.py kotlin-test --platform android
