name: Kotlin Desktop

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          name: "Windows Latest MSVC",
          os: windows-latest
        }
        - {
          name: "Ubuntu Latest GCC",
          os: ubuntu-latest
        }
        - {
          name: "macOS Latest Clang",
          os: macos-latest
        }

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Python Requirements
        run: |
          python3 -m venv .venv
          if [ "$RUNNER_OS" == "Windows" ]; then
            .venv\Scripts\activate
            python -m pip install -r requirements.txt
            echo "$PWD\.venv\Scripts" >> $GITHUB_PATH
          else
            source .venv/bin/activate
            python3 -m pip install -r requirements.txt
            echo "$PWD/.venv/bin" >> $GITHUB_PATH
          fi

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.30.0"

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: "1.10.0"

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Verify
        run: |
          python3 --version
          cmake --version
          ninja --version
          java -version

      - name: Conan (only when use conan)
        run: python3 xplpc.py conan-setup

      - name: Build
        run: python3 xplpc.py kotlin-build --platform desktop

      - name: Test
        run: python3 xplpc.py kotlin-test --platform desktop

      - name: Build JAR
        run: python3 xplpc.py kotlin-build-jar --platform desktop
