name: Swift

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS Latest Clang",
            os: macos-latest
          }

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: getsentry/action-setup-venv@v2.2.0
        with:
          python-version: "3.10"
          cache-dependency-path: requirements.txt
          install-cmd: pip install -r requirements.txt

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.30.0"

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: "1.10.0"

      - name: Verify
        run: |
          python3 --version
          cmake --version
          ninja --version

      - name: Conan
        run: python3 xplpc.py conan-setup

      - name: Test
        run: python3 xplpc.py swift-test

      - name: Build
        run: python3 xplpc.py swift-build --platform ios

      - name: Generate XCFramework
        run: python3 xplpc.py swift-build-xcframework --platform ios
